language: generic
sudo: required

# TODO: figure out why submodule checkout fails
git:
  submodules: false

branches:
  only:
    - master
    - feature/ci-dev


matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode12.2 # macOS 10.15.7
      env: >-
          CACHE_NAME=OSX_FAST_BUILD

    - os: linux
      dist: xenial
      env: >-
          CACHE_NAME=LINUX_FAST_BUILD

cache:
  # https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
  directories:
    - $HOME/.rustup
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/c2rust-ast-importer/target.travis
    - $TRAVIS_BUILD_DIR/c2rust-refactor/target

install:
  - /usr/bin/env python3 --version
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade python
      ./scripts/provision_mac.sh
      export LLVM_CONFIG_PATH=$(brew --prefix llvm@11)/bin/llvm-config
      echo $LLVM_CONFIG_PATH
      ls -la $LLVM_CONFIG_PATH
    else
      sudo -H ./scripts/provision_deb.sh
      ./scripts/provision_rust.sh
    fi
  - . ~/.cargo/env

# NOTE: travis doesn't automatically terminate if command fails.
script:
  - |
    cargo build || travis_terminate 1
    python3 ./scripts/test_translator.py --debug ./tests || travis_terminate 1

notifications:
  slack:
    secure: tSmfSUIJJdTUf+UH5iMvwFs5QIwMtoyqUqOaVN4RyBTxhOJ9BesDFAqAY2urDSGnRV5zzkHa29GavYQJc+Gfjw6++Op+4h0cWrNk6k/I204LY4+TCVsx5zBo77Qt6NdPtP1ym78jvKxkct7yZLxc6RKu+eaLYFNgVryURPdVs8qjLtkcYoo6RYZ9841R6ZR9k/tTuL8binWGLelQTFALTiJJl8C0gDE03t35snxlkKAAOdZM5n5O+fA7h/PfZUvLtVAQwOMgynQG/uj7AZAFHaVvmPw4VhYqr55dOyLfuD176ZLNE4Tt4GDO6nm+MqQAVBLb72D1c7h4MsFGOEFGLiR+Z77w748M4BYeowZILbVXko0H5BYvVae/Alh2SQiD/f+JNe2SKCTl4uKzHErWLnFbJmz0TsCZHUhkZHQ4lY+3jmRffUetHRbJ+sS0jB1a7vigWivrkDSPJmIphLdVnqgKQlRnTvj3/oKKnm1GFUUvgwEWHES7I1+IPuYYk3bI2/XDKqbTFYf1+DoLYl8tTe2DQDIUMasmy+A72pLImKN0gY6klQpPmHdtBmsaJrIajsYG2rsrEnvsVdxfc9YEE2jeY67l0HHoWeoH/YCVay2f3PQmzMbjd8cRMFgJRz9yjvgw5mquydOnAPvrot6orU2hY2/PBUv43ZmVbb6bvMA=
  email: false
