trigger:
  branches:
    include:
    - master
    - feature/ci-dev
  paths:
    exclude:
    - README.md
    - LICENSE
    - .travis.yml
    - book.toml
    - docker/*
    - manual/*
    - docs/*

jobs:
- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      arch:
        containerImage: immunant/c2rust:archlinux-base-latest
      debian10:
        containerImage: immunant/c2rust:debian-buster-latest
      debian11:
        containerImage: immunant/c2rust:debian-bullseye-latest
      fedora34:
        containerImage: immunant/c2rust:fedora-34-latest
      ubuntu20:
        containerImage: immunant/c2rust:ubuntu-focal-latest
      ubuntu18:
        containerImage: immunant/c2rust:ubuntu-bionic-latest
  container: $[ variables['containerImage'] ]
  steps:
  - script: |
      # rust was installed for the `docker` user, not the user azure creates
      # but cargo and rustup can be controlled via $CARGO_HOME and $RUSTUP_HOME.
      # NOTE: $HOME is not set correctly for the azure user; don't rely on it.
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      cargo build --release
    displayName: 'Fast build against host clang/LLVM'

  - script: |
      export PATH="/home/docker/.cargo/bin:$PATH"
      export RUSTUP_HOME=/home/docker/.rustup
      export CARGO_HOME=$AGENT_TEMPDIRECTORY/.cargo
      python3 ./scripts/test_translator.py ./tests
    displayName: 'Test translator (fast build)'

- job: Darwin
  timeoutInMinutes: 180
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      ./scripts/provision_mac.sh
      # speeds up provisioning
      export HOMEBREW_NO_AUTO_UPDATE=1
      # helps the `curl-sys` create determine how to link in libcurl.
      brew install pkg-config
      # we want to use the host curl because it has the `HTTP2` feature
      # whereas the brew version does not, this causes curl-sys to
      # build its own curl which then fails to link on Azure Devops.
      brew remove curl
      # prepare environment for the following steps
      source $HOME/.cargo/env
      brew info llvm
    displayName: 'Provision macOS'

  - script: |
      export LLVM_CONFIG_PATH=$(brew --prefix llvm)/bin/llvm-config
      cargo build --release
    displayName: 'Fast build against host clang/LLVM'

  - script: python3 ./scripts/test_translator.py  ./tests
    displayName: 'Test translator (fast build)'
