[package]
name = "c2rust-xcheck-backend-zstd-logging"
description = "Compressed logging backend for C2Rust cross-checking"
version = "0.9.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "c2rust-xcheck-zstd-printer"
path = "src/bin/printer.rs"

[dependencies]
lazy_static = "1.1.0"
zstd = "0.4"
libc = "0.2.50"
