[package]
name = "c2rust"
description = "C to Rust translation, refactoring, and cross-checking"
version = "0.9.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
edition = "2018"


[dependencies]
clap = {version = "2.33", features = ["yaml"]}
log = "0.4.0"
env_logger = "0.6.0"
regex = "1"
shlex = "0.1.1"
c2rust-transpile = { version = "0.9.0", path = "../c2rust-transpile" }
c2rust-refactor = { version = "0.9.0", path = "../c2rust-refactor" }

[features]
# Force static linking of LLVM
llvm-static = ["c2rust-transpile/llvm-static"]
